name: Deploy on Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Build Solution and SDK Core
      run: |
        dotnet build --configuration Release
        dotnet test --no-restore

        cd GMB.Sdk.Core
        dotnet build --configuration Release
        dotnet test --no-restore

    - name: Publish Microservices to Azure
      run: |
        az webapp deployment source config-zip --resource-group NOTE-GOOGLE --name vasano-business-service --src GMB.BusinessService.Api/bin/Release/net8.0/publish.zip
        az webapp deployment source config-zip --resource-group NOTE-GOOGLE --name vasano-place-service --src GMB.PlaceService.Api/bin/Release/net8.0/publish.zip
        az webapp deployment source config-zip --resource-group NOTE-GOOGLE --name vasano-scanner-service --src GMB.ScannerService.Api/bin/Release/net8.0/publish.zip
        az webapp deployment source config-zip --resource-group NOTE-GOOGLE --name vasano-user-service --src GMB.UserService.Api/bin/Release/net8.0/publish.zip
